id = "neko-dark"
name = "Neko (Dark)"
version = "1.0.0"
schema_version = 1
authors = [
    "Andrew Lake <andrew@zealsprince.com>"
    "Taha YVR <taha@noiserandom.com>"
]
description = "A low-distraction dark theme for Zed."
repository = "https://github.com/zealsprince/neko-zed-dark"
